# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core.comms_core.proto.terminalez.terminalez_pb2 as terminalez__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in terminalez_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TerminalEzStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateConnection = channel.unary_unary(
                '/terminalEz.TerminalEz/InitiateConnection',
                request_serializer=terminalez__pb2.InitialConnectionRequest.SerializeToString,
                response_deserializer=terminalez__pb2.InitialConnectionResponse.FromString,
                _registered_method=True)
        self.Channel = channel.stream_stream(
                '/terminalEz.TerminalEz/Channel',
                request_serializer=terminalez__pb2.ClientUpdate.SerializeToString,
                response_deserializer=terminalez__pb2.ServerUpdate.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/terminalEz.TerminalEz/Close',
                request_serializer=terminalez__pb2.CloseRequest.SerializeToString,
                response_deserializer=terminalez__pb2.CloseResponse.FromString,
                _registered_method=True)


class TerminalEzServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitiateConnection(self, request, context):
        """Create a new SSH session for a given computer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Channel(self, request_iterator, context):
        """Stream real-time commands and terminal outputs to the session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Gracefully shut down an existing SSH session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalEzServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateConnection,
                    request_deserializer=terminalez__pb2.InitialConnectionRequest.FromString,
                    response_serializer=terminalez__pb2.InitialConnectionResponse.SerializeToString,
            ),
            'Channel': grpc.stream_stream_rpc_method_handler(
                    servicer.Channel,
                    request_deserializer=terminalez__pb2.ClientUpdate.FromString,
                    response_serializer=terminalez__pb2.ServerUpdate.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=terminalez__pb2.CloseRequest.FromString,
                    response_serializer=terminalez__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terminalEz.TerminalEz', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terminalEz.TerminalEz', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TerminalEz(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitiateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terminalEz.TerminalEz/InitiateConnection',
            terminalez__pb2.InitialConnectionRequest.SerializeToString,
            terminalez__pb2.InitialConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Channel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/terminalEz.TerminalEz/Channel',
            terminalez__pb2.ClientUpdate.SerializeToString,
            terminalez__pb2.ServerUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terminalEz.TerminalEz/Close',
            terminalez__pb2.CloseRequest.SerializeToString,
            terminalez__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
